trigger:
- master
pool: Azure Pipelines
steps:
- task: Maven@3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
